import React from "react";
import ArtifactCard from "../components/ArtifactCard.jsx";
import ArtifactPreviewDrawer from "../components/ArtifactPreviewDrawer.jsx";
import StatCard from "../components/StatCard.jsx";
import { ARTIFACT_TYPES } from "../constants/pipeline.js";
import { useArtifacts } from "../hooks/useArtifacts.js";

export default function Artifacts() {
  const {
    tasks,
    taskRequestById,
    artifacts,
    totalCount,
    isLoading,
    error,
    taskFilter,
    setTaskFilter,
    agentFilter,
    setAgentFilter,
    search,
    setSearch,
    ensureContent,
    openPreview,
    closePreview,
    previewArtifact,
    previewState,
    refresh,
  } = useArtifacts();

  const reusedCount = artifacts.filter((a) => a.reused_content).length;
  const distinctTasks = new Set(artifacts.map((a) => a.task_id)).size;

  return (
    <div className="h-full w-full flex flex-col bg-slate-50 dark:bg-[#0b0d13] text-slate-900 dark:text-slate-100 transition-colors">
      <div className="flex-1 min-h-0 overflow-y-auto p-4 space-y-4">
        {/* Header */}
        <div className="flex items-center justify-between gap-3">
          <div>
            <h1 className="text-base font-bold">Artifacts</h1>
            <p className="text-xs text-slate-500">
              Reusable SDLC deliverables generated by each agent — project plan, requirements,
              architecture, implementation plan, review report, test plan, and documentation.
            </p>
          </div>
          <button
            type="button"
            onClick={refresh}
            className="shrink-0 text-xs font-medium px-3 py-2 rounded-lg border border-slate-300 dark:border-white/10 text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-white/10 transition-colors"
          >
            Refresh
          </button>
        </div>

        {/* Stats strip */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          <StatCard label="Total Artifacts" value={totalCount} />
          <StatCard label="Matching Filters" value={artifacts.length} accent />
          <StatCard label="Reused via Cache" value={reusedCount} hint="identical content deduped" />
          <StatCard label="Tasks with Artifacts" value={distinctTasks} />
        </div>

        {/* Filters */}
        <div className="bg-white dark:bg-surface rounded-xl border border-slate-200 dark:border-white/5 p-4 space-y-3">
          <div className="flex flex-col sm:flex-row gap-2">
            <input
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search by filename, agent, or task id…"
              className="flex-1 bg-slate-50 dark:bg-panel rounded-lg px-3 py-2 text-sm outline-none border border-slate-300 dark:border-white/10 focus:border-accent"
            />
            <select
              value={taskFilter}
              onChange={(e) => setTaskFilter(e.target.value)}
              className="sm:w-64 bg-slate-50 dark:bg-panel border border-slate-300 dark:border-white/10 rounded-lg px-3 py-2 text-sm outline-none focus:border-accent"
            >
              <option value="">All tasks</option>
              {tasks.map((t) => (
                <option key={t.task_id} value={t.task_id}>
                  [{t.status}] {(t.request || "").slice(0, 48)}
                </option>
              ))}
            </select>
          </div>

          <div className="flex flex-wrap gap-2">
            <button
              type="button"
              onClick={() => setAgentFilter("")}
              className={`text-xs px-2.5 py-1.5 rounded-full border transition-colors ${
                agentFilter === ""
                  ? "bg-accent text-white border-accent"
                  : "border-slate-300 dark:border-white/10 text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-white/10"
              }`}
            >
              All types
            </button>
            {ARTIFACT_TYPES.map(({ agent, label }) => (
              <button
                key={agent}
                type="button"
                onClick={() => setAgentFilter(agent)}
                className={`text-xs px-2.5 py-1.5 rounded-full border transition-colors ${
                  agentFilter === agent
                    ? "bg-accent text-white border-accent"
                    : "border-slate-300 dark:border-white/10 text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-white/10"
                }`}
              >
                {label}
              </button>
            ))}
          </div>

          {taskFilter && taskRequestById.get(taskFilter) && (
            <p className="text-xs text-slate-500 truncate">
              Showing artifacts for: <span className="italic">"{taskRequestById.get(taskFilter)}"</span>
            </p>
          )}
        </div>

        {error && <p className="text-sm text-danger">{error}</p>}

        {/* Grid */}
        {isLoading ? (
          <p className="text-sm text-slate-500 text-center py-10">Loading artifacts…</p>
        ) : artifacts.length === 0 ? (
          <div className="bg-white dark:bg-surface rounded-xl border border-slate-200 dark:border-white/5 p-10 text-center">
            <p className="text-sm text-slate-500">
              {totalCount === 0
                ? "No artifacts yet — run a workflow from the Dashboard or Workflow tab to generate SDLC deliverables."
                : "No artifacts match the current filters."}
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {artifacts.map((artifact) => (
              <ArtifactCard
                key={`${artifact.task_id}/${artifact.filename}`}
                artifact={artifact}
                onPreview={openPreview}
                ensureContent={ensureContent}
              />
            ))}
          </div>
        )}
      </div>

      <ArtifactPreviewDrawer artifact={previewArtifact} state={previewState} onClose={closePreview} />
    </div>
  );
}
